---
- name: download...
  become: yes
  become_user: root
  get_url:
    url: '{{oc_tgz_url}}'
    dest: /tmp/{{oc_tgz}}
    mode: 0644
    checksum: '{{oc_checksum}}'

- name: unarchive
  become: yes
  become_user: root
  unarchive:
    src: /tmp/{{oc_tgz}}
    dest: '{{oc_install_parent_dir}}'
    creates: '{{oc_install_dir}}'

- name: link
  become: yes
  become_user: root
  with_items:
    - oc
  file:
    src: '{{oc_install_dir}}/{{item}}'
    dest: '{{oc_install_parent_dir}}/{{item}}'
    state: link
